version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    target-branch: "main"
    # Increase the version requirements
    # only when required
    versioning-strategy: increase-if-necessary
    labels:
      - "dependencies"
      - "npm"